---

- name: install tinc
  apt: >
    name=tinc
    state=present
    update_cache=yes
    cache_valid_time=3600

- name: create /etc/tinc/nets.boot file from template
  template: >
    src=nets.boot.j2
    dest=/etc/tinc/nets.boot
  notify:
    - reload tinc

- name: ensure tinc netname directory exists
  file: >
    path=/etc/tinc/{{ netname }}/hosts
    recurse=True
    state=directory

- name: ensure tinc.conf exists for netname
  template: >
    src=tinc.conf.j2
    dest=/etc/tinc/{{ netname }}/tinc.conf

- name: create tinc-up file
  template: >
    src=tinc-up.j2
    dest=/etc/tinc/{{ netname }}/tinc-up
    mode=0755

- name: create tinc-down file
  template: >
    src=tinc-down.j2
    dest=/etc/tinc/{{ netname }}/tinc-down
    mode=0755
  notify:
    - reload tinc

- name: ensure tinc hosts file binds to physical ip address
  lineinfile: >
    dest=/etc/tinc/{{ netname }}/hosts/{{ ansible_hostname }}
    line="Address = {{ physical_ip }}"
    create=yes
  notify:
    - reload tinc

- name: ensure subnet ip address is properly set in tinc host file
  lineinfile: >
    dest=/etc/tinc/{{ netname }}/hosts/{{ ansible_hostname }}
    line="Subnet = {{ vpn_ip }}/{{ vpn_cidr_netmask }}"
    create=yes
  notify:
    - reload tinc

- name: check whether /etc/tinc/netname/hosts/ansible_hostname contains "-----END RSA PUBLIC KEY-----"
  command: awk '/^-----END RSA PUBLIC KEY-----$/'  /etc/tinc/{{ netname }}/hosts/{{ ansible_hostname }}
  changed_when: "public_key.stdout != '-----END RSA PUBLIC KEY-----'"
  register: public_key

# this is necessary because the public key will not be generated (non-interactively) if the private key already exists
- name: delete private key and regenerate keypair if public key is absent from tinc hosts file
  file: >
    path=/etc/tinc/{{ netname }}/rsa_key.priv
    state=absent
  when: public_key.changed

- name: create tinc private key (and append public key to tincd hosts file)
  shell: tincd -n {{ netname }} -K4096
  args:
    creates: /etc/tinc/{{ netname }}/rsa_key.priv
  notify:
    - reload tinc

- name: fetch tinc hosts file after key creation
  fetch: >
    src=/etc/tinc/{{ netname }}/hosts/{{ ansible_hostname }}
    dest=fetch/{{ ansible_hostname }}
    flat=yes
  notify:
    - reload tinc

- name: sync the fetched hosts files on each host
  synchronize: >
    src=fetch/
    dest=/etc/tinc/{{ netname }}/hosts/
  notify:
    - reload tinc

- name: ensure tinc is running
  service: >
    name=tinc
    enabled=yes
    state=started
    pattern=tincd -n {{ netname }}

